// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc2DDxzECTh9tmB3_uI6v9_E27wSik4Jo',
    appId: '1:1078413761432:web:ac1ac1c071302b8bee69ed',
    messagingSenderId: '1078413761432',
    projectId: 'to-do-liiiiiist-11',
    authDomain: 'to-do-liiiiiist-11.firebaseapp.com',
    storageBucket: 'to-do-liiiiiist-11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK1I8D0WzJmZrW6rPkeLFZ_Y7dgU18O_k',
    appId: '1:1078413761432:android:d807eeddd8b5ac74ee69ed',
    messagingSenderId: '1078413761432',
    projectId: 'to-do-liiiiiist-11',
    storageBucket: 'to-do-liiiiiist-11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6r0bT7y95iA05lza8wdjaEL9NN-mIqMw',
    appId: '1:1078413761432:ios:8c1a93c18165d1d4ee69ed',
    messagingSenderId: '1078413761432',
    projectId: 'to-do-liiiiiist-11',
    storageBucket: 'to-do-liiiiiist-11.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6r0bT7y95iA05lza8wdjaEL9NN-mIqMw',
    appId: '1:1078413761432:ios:8c1a93c18165d1d4ee69ed',
    messagingSenderId: '1078413761432',
    projectId: 'to-do-liiiiiist-11',
    storageBucket: 'to-do-liiiiiist-11.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc2DDxzECTh9tmB3_uI6v9_E27wSik4Jo',
    appId: '1:1078413761432:web:5bddccbcea096d60ee69ed',
    messagingSenderId: '1078413761432',
    projectId: 'to-do-liiiiiist-11',
    authDomain: 'to-do-liiiiiist-11.firebaseapp.com',
    storageBucket: 'to-do-liiiiiist-11.appspot.com',
  );

  
}




